const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const env = require("../../config/env");
const AppError = require("../../errors/AppError");
const buildPagination = require("../../utils/pagination");
const { ROLES } = require("../../constants/roles");
const { USER_STATUSES } = require("../../constants/statuses");
const userRepository = require("../users/user.repository");
const jobRepository = require("../jobs/job.repository");
const jobService = require("../jobs/job.service");
const bookingRepository = require("../bookings/booking.repository");
const bookingService = require("../bookings/booking.service");
const paymentRepository = require("../payments/payment.repository");
const paymentService = require("../payments/payment.service");
const applicationRepository = require("../applications/application.repository");
const supportRepository = require("../support/support.repository");
const contentRepository = require("../content/content.repository");
const authSessionRepository = require("../auth/auth-session.repository");
const testimonialRepository = require("../testimonials/testimonial.repository");
const notificationService = require("../notifications/notification.service");
const emailService = require("../../services/email.service");
const {
  getPricingConfig,
  savePricingConfig,
} = require("../payments/pricing-engine");
const {
  DEFAULT_LEGAL_DOCS,
  getDefaultLegalDocs,
  isLegacyAutoGeneratedLegalBody,
  isPlaceholderLegalBody,
  normalizeTermsLegalBody,
} = require("../../constants/legal-documents");
const {
  buildRoleMembershipFilter,
  combineMongoFilters,
  hasRole,
} = require("../../utils/user-roles");

const DEFAULT_PLATFORM_SETTINGS = {
  name: "Yard Heroes",
  email: "support@yardheroes.com",
  phone: "+1 (555) 123-4567",
};

const DEFAULT_PAYMENT_SETTINGS = {
  platformFee: env.defaultPlatformFeePercentage,
  minimumServiceAmount: 25,
  paymentProcessor: "stripe",
};

const DEFAULT_NOTIFICATION_SETTINGS = {
  newUserRegistrations: true,
  serviceCompletions: true,
  paymentIssues: true,
};

const escapeRegex = (value = "") =>
  String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const DASHBOARD_STATS_CACHE_TTL_MS = 30 * 1000;
let dashboardStatsCache = {
  data: null,
  expiresAt: 0,
  pending: null,
};

class AdminService {
  getVisibleUsersFilter(filter = {}) {
    return {
      isDeleted: { $ne: true },
      ...filter,
    };
  }

  buildSearchFilter(query = {}, fields = []) {
    if (!query.search) {
      return {};
    }

    return {
      $or: fields.map((field) => ({
        [field]: { $regex: query.search, $options: "i" },
      })),
    };
  }

  getDefaultLegalDocs() {
    return getDefaultLegalDocs();
  }

  normalizePlatformSettings(settings = {}) {
    return {
      name: String(settings.name ?? DEFAULT_PLATFORM_SETTINGS.name).trim(),
      email: String(settings.email ?? DEFAULT_PLATFORM_SETTINGS.email)
        .trim()
        .toLowerCase(),
      phone: String(settings.phone ?? DEFAULT_PLATFORM_SETTINGS.phone).trim(),
    };
  }

  normalizePaymentSettings(settings = {}) {
    const minimumServiceAmount = Number(
      settings.minimumServiceAmount ?? DEFAULT_PAYMENT_SETTINGS.minimumServiceAmount
    );
    const paymentProcessor = String(
      settings.paymentProcessor ?? DEFAULT_PAYMENT_SETTINGS.paymentProcessor
    )
      .trim()
      .toLowerCase();

    return {
      platformFee: DEFAULT_PAYMENT_SETTINGS.platformFee,
      minimumServiceAmount:
        Number.isFinite(minimumServiceAmount) && minimumServiceAmount >= 0
          ? minimumServiceAmount
          : 0,
      paymentProcessor: paymentProcessor || DEFAULT_PAYMENT_SETTINGS.paymentProcessor,
    };
  }

  normalizeNotificationSettings(settings = {}) {
    return {
      newUserRegistrations: Boolean(
        settings.newUserRegistrations ?? DEFAULT_NOTIFICATION_SETTINGS.newUserRegistrations
      ),
      serviceCompletions: Boolean(
        settings.serviceCompletions ?? DEFAULT_NOTIFICATION_SETTINGS.serviceCompletions
      ),
      paymentIssues: Boolean(settings.paymentIssues ?? DEFAULT_NOTIFICATION_SETTINGS.paymentIssues),
    };
  }

  normalizeLegalDocs(documents = []) {
    const sourceDocuments =
      Array.isArray(documents) && documents.length ? documents : this.getDefaultLegalDocs();

    return sourceDocuments.map((document, index) => {
      const fallbackDocument = DEFAULT_LEGAL_DOCS[index] || {};
      const normalizedStatus =
        String(document?.status || fallbackDocument.status || "active").toLowerCase() ===
        "inactive"
          ? "inactive"
          : "active";
      const rawBody = String(document?.body || "").trim();
      const shouldUseFallbackBody =
        !rawBody ||
        isPlaceholderLegalBody(rawBody) ||
        isLegacyAutoGeneratedLegalBody(fallbackDocument.id, rawBody);
      const rawName = String(document?.name || "").trim();
      const shouldUseFallbackName =
        !rawName ||
        (fallbackDocument.id === "terms-of-service" &&
          shouldUseFallbackBody &&
          /^terms of service$/i.test(rawName));

      return {
        id: String(document?.id || fallbackDocument.id || `document-${index + 1}`).trim(),
        name: String(
          shouldUseFallbackName ? fallbackDocument.name : rawName || fallbackDocument.name || `Document ${index + 1}`
        ).trim(),
        status: normalizedStatus,
        body: normalizeTermsLegalBody(
          fallbackDocument.id,
          shouldUseFallbackBody ? fallbackDocument.body : rawBody
        ),
      };
    });
  }

  async getAdminProfile(adminUserId) {
    const adminUser = await userRepository.findOne(
      combineMongoFilters(
        this.getVisibleUsersFilter({ _id: adminUserId }),
        buildRoleMembershipFilter(ROLES.ADMIN)
      ),
      {
        select: "name email phone profilePhotoUrl lastLoginAt role roles status",
        lean: true,
      }
    );

    if (!adminUser || !hasRole(adminUser, ROLES.ADMIN)) {
      throw new AppError("Admin not found", 404);
    }

    return adminUser;
  }

  async seedAdmin() {
    const existingAdminCount = await userRepository.count(buildRoleMembershipFilter(ROLES.ADMIN));

    if (existingAdminCount > 0) {
      return {
        status: "skipped",
        reason: "admin_exists",
      };
    }

    if (!env.adminPassword) {
      throw new AppError(
        "ADMIN_PASSWORD is required to seed the initial admin account",
        500
      );
    }

    const [existingEmailUser, existingPhoneUser] = await Promise.all([
      userRepository.findByEmail(env.adminEmail),
      userRepository.findByPhone(env.adminPhone),
    ]);

    if (existingEmailUser) {
      throw new AppError(
        `Cannot seed admin because ${env.adminEmail} is already assigned to another account`,
        409
      );
    }

    if (existingPhoneUser) {
      throw new AppError(
        `Cannot seed admin because ${env.adminPhone} is already assigned to another account`,
        409
      );
    }

    const hashedPassword = await bcrypt.hash(env.adminPassword, 10);

    let admin;

    try {
      admin = await userRepository.create({
        name: env.adminName,
        email: env.adminEmail,
        phone: env.adminPhone,
        password: hashedPassword,
        emailVerifiedAt: new Date(),
        role: ROLES.ADMIN,
        roles: [ROLES.ADMIN],
        status: "active",
        workerStatus: "not_applicable",
      });
    } catch (error) {
      if (error?.code === 11000) {
        const adminCountAfterConflict = await userRepository.count(
          buildRoleMembershipFilter(ROLES.ADMIN)
        );

        if (adminCountAfterConflict > 0) {
          return {
            status: "skipped",
            reason: "admin_exists",
          };
        }
      }

      throw error;
    }

    return {
      status: "created",
      adminId: String(admin._id),
      email: admin.email,
    };
  }

  async getDashboardRecentBookings(limit = 5) {
    return jobRepository.model
      .find({})
      .sort({ createdAt: -1 })
      .limit(limit)
      .select("title serviceType status customer assignedWorker createdAt")
      .populate([
        {
          path: "customer",
          select: "name email phone",
        },
        {
          path: "assignedWorker",
          select: "name email phone workerStatus skills",
        },
      ])
      .lean();
  }

  async getDashboardRecentHeroApplications(limit = 5) {
    return userRepository.model
      .find(
        combineMongoFilters(
          this.getVisibleUsersFilter({}),
          buildRoleMembershipFilter(ROLES.WORKER)
        )
      )
      .sort({ createdAt: -1 })
      .limit(limit)
      .select("name email workerStatus status location profilePhotoUrl createdAt")
      .lean();
  }

  countDocuments(model, filter = {}, options = {}) {
    const query = model.countDocuments(filter);

    if (options.hint) {
      query.hint(options.hint);
    }

    return query;
  }

  getDashboardUserStats() {
    const visibleUsersFilter = this.getVisibleUsersFilter({});
    const heroFilter = combineMongoFilters(
      visibleUsersFilter,
      buildRoleMembershipFilter(ROLES.WORKER)
    );
    const customerFilter = combineMongoFilters(
      visibleUsersFilter,
      buildRoleMembershipFilter(ROLES.CUSTOMER)
    );

    return Promise.all([
      this.countDocuments(userRepository.model, visibleUsersFilter),
      this.countDocuments(userRepository.model, heroFilter),
      this.countDocuments(
        userRepository.model,
        combineMongoFilters(heroFilter, {
          workerStatus: "approved",
          status: "active",
        })
      ),
      this.countDocuments(
        userRepository.model,
        combineMongoFilters(heroFilter, {
          workerStatus: "pending",
        })
      ),
      this.countDocuments(userRepository.model, customerFilter),
      this.countDocuments(
        userRepository.model,
        combineMongoFilters(customerFilter, {
          status: "active",
        })
      ),
    ]).then(
      ([
        totalUsers,
        totalHeroes,
        activeHeroes,
        pendingHeroes,
        totalCustomers,
        activeCustomers,
      ]) => ({
        totalUsers,
        totalHeroes,
        activeHeroes,
        pendingHeroes,
        totalCustomers,
        activeCustomers,
      })
    );
  }

  getDashboardJobStats() {
    return Promise.all([
      this.countDocuments(jobRepository.model, {}, { hint: { _id: 1 } }),
      this.countDocuments(jobRepository.model, {
        status: "new",
        assignedWorker: null,
      }),
    ]).then(([totalJobs, pendingJobs]) => ({
      totalJobs,
      pendingJobs,
    }));
  }

  async getDashboardPaymentStats() {
    const [totalPayments, paidSummaryResult] = await Promise.all([
      this.countDocuments(paymentRepository.model, {}, { hint: { _id: 1 } }),
      paymentRepository.model.aggregate([
        {
          $match: {
            status: "paid",
          },
        },
        {
          $project: {
            amount: { $ifNull: ["$amount", 0] },
            platformFee: { $ifNull: ["$platformFee", 0] },
            bookingFee: { $ifNull: ["$bookingFee", 0] },
            workerPayout: { $ifNull: ["$workerPayout", 0] },
          },
        },
        {
          $group: {
            _id: null,
            totalAmount: { $sum: "$amount" },
            totalPlatformFee: { $sum: { $add: ["$platformFee", "$bookingFee"] } },
            totalBookingFee: { $sum: "$bookingFee" },
            totalHeroPayout: { $sum: "$workerPayout" },
          },
        },
      ]),
    ]);
    const paidSummary = paidSummaryResult[0] || {};

    return {
      totalPayments,
      totalAmount: paidSummary.totalAmount || 0,
      totalPlatformFee: paidSummary.totalPlatformFee || 0,
      totalBookingFee: paidSummary.totalBookingFee || 0,
      totalHeroPayout: paidSummary.totalHeroPayout || 0,
    };
  }

  async buildDashboardStats() {
    const [
      userStats,
      jobStats,
      totalBookings,
      paymentStats,
      totalSupportConversations,
      recentBookings,
      recentHeroApplications,
    ] = await Promise.all([
      this.getDashboardUserStats(),
      this.getDashboardJobStats(),
      this.countDocuments(bookingRepository.model, {}, { hint: { _id: 1 } }),
      this.getDashboardPaymentStats(),
      this.countDocuments(supportRepository.model, {}, { hint: { _id: 1 } }),
      this.getDashboardRecentBookings(),
      this.getDashboardRecentHeroApplications(),
    ]);

    return {
      totalUsers: userStats.totalUsers,
      totalHeroes: userStats.totalHeroes,
      activeHeroes: userStats.activeHeroes,
      pendingHeroes: userStats.pendingHeroes,
      totalCustomers: userStats.totalCustomers,
      activeCustomers: userStats.activeCustomers,
      totalJobs: jobStats.totalJobs,
      pendingJobs: jobStats.pendingJobs,
      totalBookings,
      totalPayments: paymentStats.totalPayments,
      totalSupportConversations,
      totalRevenue: paymentStats.totalAmount,
      totalPlatformFee: paymentStats.totalPlatformFee,
      totalBookingFee: paymentStats.totalBookingFee,
      totalHeroPayout: paymentStats.totalHeroPayout,
      recentBookings,
      recentHeroApplications,
    };
  }

  async getDashboardStats() {
    const now = Date.now();

    if (dashboardStatsCache.data && dashboardStatsCache.expiresAt > now) {
      return dashboardStatsCache.data;
    }

    if (!dashboardStatsCache.pending) {
      dashboardStatsCache.pending = this.buildDashboardStats()
        .then((stats) => {
          dashboardStatsCache = {
            data: stats,
            expiresAt: Date.now() + DASHBOARD_STATS_CACHE_TTL_MS,
            pending: null,
          };

          return stats;
        })
        .catch((error) => {
          const staleStats = dashboardStatsCache.data;
          dashboardStatsCache.pending = null;

          if (staleStats) {
            return staleStats;
          }

          throw error;
        });
    }

    return dashboardStatsCache.pending;
  }

  async listHeroes(query = {}) {
    const pagination = buildPagination(query);
    const filter = this.getVisibleUsersFilter({
      ...this.buildSearchFilter(query, ["name", "email", "phone"]),
    });

    if (query.status) {
      filter.workerStatus = query.status;
    }

    if (query.skill) {
      filter.skills = query.skill;
    }

    return userRepository.listHeroes(filter, {
      ...pagination,
      sort: { createdAt: -1 },
      select: "-password",
    });
  }

  async getHeroFilters() {
    const skills = await userRepository.model.distinct("skills", {
      $and: [
        { isDeleted: { $ne: true } },
        buildRoleMembershipFilter(ROLES.WORKER),
        { skills: { $exists: true, $ne: [] } },
      ],
    });

    return {
      skills: skills.filter(Boolean).sort((left, right) => left.localeCompare(right)),
    };
  }

  async getHeroById(workerId) {
    const worker = await userRepository.findOne(this.getVisibleUsersFilter({ _id: workerId }), {
      select: "-password",
    });
    if (!worker || !hasRole(worker, ROLES.WORKER)) {
      throw new AppError("Hero not found", 404);
    }

    return worker;
  }

  async updateHeroStatus(workerId, workerStatus) {
    const worker = await this.getHeroById(workerId);
    const shouldSendApprovalEmail =
      workerStatus === "approved" && worker.workerStatus !== "approved";
    await userRepository.updateById(worker._id, { workerStatus });
    const updatedHero = await this.getHeroById(worker._id);
    await Promise.allSettled([
      notificationService.createForUser(updatedHero, {
        type: `worker_status_${workerStatus}`,
        recipientRole: ROLES.WORKER,
        category: "account",
        title:
          workerStatus === "approved"
            ? "Hero application approved"
            : "Hero application updated",
        message:
          workerStatus === "approved"
            ? "Your Hero application was approved. You can now accept jobs."
            : "Your Hero application was rejected. Please review your details and try again.",
        link: workerStatus === "approved" ? "/worker-home" : "/registration",
        entityType: "user",
        entityId: String(updatedHero._id),
      }),
      shouldSendApprovalEmail
        ? emailService.sendWorkerWelcomeEmail({
            to: updatedHero.email,
            name: updatedHero.name,
          })
        : Promise.resolve(),
    ]);
    return updatedHero;
  }

  async updateHeroAccountStatus(workerId, status) {
    const worker = await this.getHeroById(workerId);

    if (!USER_STATUSES.includes(status)) {
      throw new AppError("Invalid Hero account status", 400);
    }

    await userRepository.updateById(worker._id, { status });
    const updatedHero = await this.getHeroById(worker._id);
    await Promise.allSettled([
      notificationService.createForUser(updatedHero, {
        type: "worker_account_status_updated",
        recipientRole: ROLES.WORKER,
        category: "account",
        title: "Account status updated",
        message: `An admin changed your account status to ${status}.`,
        link: "/registration",
        entityType: "user",
        entityId: String(updatedHero._id),
      }),
    ]);
    return updatedHero;
  }

  async deleteHero(adminUser, workerId) {
    if (!hasRole(adminUser, ROLES.ADMIN)) {
      throw new AppError("Only admins can delete Heroes", 403);
    }

    const worker = await this.getHeroById(workerId);
    const [inProgressJobs, inProgressBookings, acceptedJobs, acceptedBookings] = await Promise.all([
      jobRepository.findMany(
        { assignedWorker: worker._id, status: { $in: ["in_progress", "pending_verification"] } },
        { lean: true, select: "_id" }
      ),
      bookingRepository.findMany(
        { worker: worker._id, status: { $in: ["in_progress", "pending_verification"] } },
        { lean: true, select: "_id" }
      ),
      jobRepository.findMany(
        { assignedWorker: worker._id, status: "assigned" },
        { lean: true, select: "_id" }
      ),
      bookingRepository.findMany(
        { worker: worker._id, status: "assigned" },
        { lean: true, select: "_id job" }
      ),
    ]);

    if (inProgressJobs.length || inProgressBookings.length) {
      throw new AppError(
        "This Hero has work in progress. Complete or cancel those bookings before deleting the profile.",
        409
      );
    }

    const acceptedBookingIds = acceptedBookings.map((booking) => booking._id);
    const acceptedJobIds = [...new Set(
      [...acceptedJobs.map((job) => job._id), ...acceptedBookings.map((booking) => booking.job)].filter(
        Boolean
      )
    )];
    const now = new Date();
    const deletionReason = "Hero profile deleted by admin";
    const replacementPasswordHash = await bcrypt.hash(
      `deleted-worker-${worker._id}-${Date.now()}`,
      10
    );

    if (acceptedBookingIds.length > 0) {
      await Promise.all([
        bookingRepository.updateMany(
          { _id: { $in: acceptedBookingIds } },
          {
            status: "cancelled",
            cancelReason: deletionReason,
            cancelledAt: now,
          }
        ),
        jobRepository.updateMany(
          { _id: { $in: acceptedJobIds } },
          {
            assignedWorker: null,
            status: "new",
            cancelReason: deletionReason,
          }
        ),
        paymentRepository.updateMany(
          {
            $or: [
              { booking: { $in: acceptedBookingIds } },
              { job: { $in: acceptedJobIds }, worker: worker._id },
            ],
          },
          {
            booking: null,
            worker: null,
          }
        ),
      ]);
    }

    await Promise.all([
      applicationRepository.deleteMany({ worker: worker._id }),
      authSessionRepository.revokeAllByUser(worker._id, "admin_worker_delete"),
      userRepository.updateById(worker._id, {
        $set: {
          name: "Deleted Hero",
          email: `deleted-worker-${String(worker._id).toLowerCase()}@yardheroes.local`,
          phone: `deleted-${String(worker._id)}`,
          password: replacementPasswordHash,
          status: "inactive",
          workerStatus: "rejected",
          skills: [],
          profilePhotoUrl: "",
          idDocumentUrl: "",
          isDeleted: true,
          deletedAt: now,
          deletedBy: adminUser._id,
          lastLoginAt: null,
        },
        $unset: {
          age: 1,
          location: 1,
          availability: 1,
        },
      }),
      supportRepository.updateMany(
        { user: worker._id },
        { user: null }
      ),
    ]);

    return {
      deletedHeroId: String(worker._id),
      reopenedJobs: acceptedJobIds.length,
      cancelledBookings: acceptedBookingIds.length,
    };
  }

  buildCustomerListFilter(query = {}) {
    const filter = combineMongoFilters(
      this.buildSearchFilter(query, ["name", "email", "phone"]),
      buildRoleMembershipFilter(ROLES.CUSTOMER)
    );

    if (USER_STATUSES.includes(query.status)) {
      filter.status = query.status;
    }

    return filter;
  }

  getCustomerListSort(sortValue = "newest") {
    switch (String(sortValue || "newest").toLowerCase()) {
      case "oldest":
        return { createdAt: 1, _id: 1 };
      case "most_bookings":
        return { totalBookings: -1, createdAt: -1, _id: -1 };
      case "highest_spent":
        return { totalSpent: -1, createdAt: -1, _id: -1 };
      default:
        return { createdAt: -1, _id: -1 };
    }
  }

  getTestimonialListSort(sortValue = "newest") {
    switch (String(sortValue || "newest").toLowerCase()) {
      case "oldest":
        return { updatedAt: 1, createdAt: 1, _id: 1 };
      case "highest_rating":
        return { rating: -1, updatedAt: -1, _id: -1 };
      case "lowest_rating":
        return { rating: 1, updatedAt: -1, _id: -1 };
      default:
        return { updatedAt: -1, createdAt: -1, _id: -1 };
    }
  }

  async listTestimonials(query = {}) {
    const pagination = buildPagination(query);
    const sort = this.getTestimonialListSort(query.sort);
    const skip = (pagination.page - 1) * pagination.limit;
    const normalizedSearch = String(query.search || "").trim();
    const searchMatch = {};

    if (normalizedSearch) {
      const searchPattern = { $regex: escapeRegex(normalizedSearch), $options: "i" };
      searchMatch.$or = [
        { displayName: searchPattern },
        { text: searchPattern },
        { location: searchPattern },
        { "customerAccount.name": searchPattern },
        { "customerAccount.email": searchPattern },
        { "customerAccount.phone": searchPattern },
      ];

      if (mongoose.Types.ObjectId.isValid(normalizedSearch)) {
        const searchObjectId = new mongoose.Types.ObjectId(normalizedSearch);
        searchMatch.$or.push({ _id: searchObjectId }, { customer: searchObjectId });
      }
    }

    const [result] = await testimonialRepository.model.aggregate([
      {
        $lookup: {
          from: userRepository.model.collection.name,
          localField: "customer",
          foreignField: "_id",
          as: "customerAccount",
        },
      },
      {
        $unwind: {
          path: "$customerAccount",
          preserveNullAndEmptyArrays: true,
        },
      },
      ...(normalizedSearch ? [{ $match: searchMatch }] : []),
      {
        $facet: {
          items: [
            { $sort: sort },
            { $skip: skip },
            { $limit: pagination.limit },
            {
              $project: {
                _id: 1,
                id: { $toString: "$_id" },
                customerId: {
                  $cond: [
                    { $ne: ["$customer", null] },
                    { $toString: "$customer" },
                    "",
                  ],
                },
                displayName: 1,
                rating: 1,
                text: 1,
                location: 1,
                createdAt: 1,
                updatedAt: 1,
                customer: {
                  _id: "$customerAccount._id",
                  id: {
                    $cond: [
                      { $ne: ["$customerAccount._id", null] },
                      { $toString: "$customerAccount._id" },
                      "",
                    ],
                  },
                  name: "$customerAccount.name",
                  email: "$customerAccount.email",
                  phone: "$customerAccount.phone",
                  status: "$customerAccount.status",
                  profilePhotoUrl: "$customerAccount.profilePhotoUrl",
                  emailVerifiedAt: "$customerAccount.emailVerifiedAt",
                  createdAt: "$customerAccount.createdAt",
                },
              },
            },
          ],
          totalCount: [{ $count: "count" }],
        },
      },
    ]);

    const total = result?.totalCount?.[0]?.count || 0;

    return {
      items: result?.items || [],
      pagination: {
        ...pagination,
        total,
        totalPages: Math.ceil(total / pagination.limit) || 1,
      },
    };
  }

  async listCustomers(query = {}) {
    const pagination = buildPagination(query);
    const filter = this.buildCustomerListFilter(query);
    const sort = this.getCustomerListSort(query.sort);
    const skip = (pagination.page - 1) * pagination.limit;

    const [result] = await userRepository.model.aggregate([
      {
        $match: filter,
      },
      {
        $lookup: {
          from: jobRepository.model.collection.name,
          let: { customerId: "$_id" },
          pipeline: [
            {
              $match: {
                $expr: {
                  $eq: ["$customer", "$$customerId"],
                },
              },
            },
            {
              $group: {
                _id: null,
                totalBookings: { $sum: 1 },
                lastBookingAt: { $max: "$createdAt" },
              },
            },
          ],
          as: "jobMetrics",
        },
      },
      {
        $lookup: {
          from: paymentRepository.model.collection.name,
          let: { customerId: "$_id" },
          pipeline: [
            {
              $match: {
                $expr: {
                  $eq: ["$customer", "$$customerId"],
                },
              },
            },
            {
              $group: {
                _id: null,
                totalSpent: {
                  $sum: {
                    $cond: [{ $eq: ["$status", "paid"] }, "$amount", 0],
                  },
                },
                paidOrders: {
                  $sum: {
                    $cond: [{ $eq: ["$status", "paid"] }, 1, 0],
                  },
                },
                outstandingBalance: {
                  $sum: {
                    $cond: [{ $in: ["$status", ["pending", "authorized"]] }, "$amount", 0],
                  },
                },
                lastPaymentAt: {
                  $max: {
                    $cond: [{ $eq: ["$status", "paid"] }, "$paidAt", null],
                  },
                },
              },
            },
          ],
          as: "paymentMetrics",
        },
      },
      {
        $addFields: {
          jobMetrics: {
            $ifNull: [{ $arrayElemAt: ["$jobMetrics", 0] }, {}],
          },
          paymentMetrics: {
            $ifNull: [{ $arrayElemAt: ["$paymentMetrics", 0] }, {}],
          },
        },
      },
      {
        $addFields: {
          totalBookings: { $ifNull: ["$jobMetrics.totalBookings", 0] },
          lastBookingAt: "$jobMetrics.lastBookingAt",
          totalSpent: { $ifNull: ["$paymentMetrics.totalSpent", 0] },
          paidOrders: { $ifNull: ["$paymentMetrics.paidOrders", 0] },
          outstandingBalance: {
            $ifNull: ["$paymentMetrics.outstandingBalance", 0],
          },
          lastPaymentAt: "$paymentMetrics.lastPaymentAt",
        },
      },
      {
        $addFields: {
          averageOrder: {
            $cond: [
              { $gt: ["$paidOrders", 0] },
              { $divide: ["$totalSpent", "$paidOrders"] },
              0,
            ],
          },
        },
      },
      {
        $project: {
          name: 1,
          email: 1,
          phone: 1,
          status: 1,
          location: 1,
          profilePhotoUrl: 1,
          createdAt: 1,
          lastLoginAt: 1,
          totalBookings: 1,
          totalSpent: 1,
          outstandingBalance: 1,
          averageOrder: 1,
          lastBookingAt: 1,
          lastPaymentAt: 1,
        },
      },
      {
        $sort: sort,
      },
      {
        $facet: {
          items: [{ $skip: skip }, { $limit: pagination.limit }],
          totalCount: [{ $count: "count" }],
        },
      },
    ]);

    const total = result?.totalCount?.[0]?.count || 0;

    return {
      items: result?.items || [],
      pagination: {
        ...pagination,
        total,
        totalPages: Math.ceil(total / pagination.limit) || 1,
      },
    };
  }

  async getCustomerById(customerId) {
    if (!mongoose.Types.ObjectId.isValid(customerId)) {
      throw new AppError("Customer not found", 404);
    }

    const normalizedCustomerId = new mongoose.Types.ObjectId(customerId);
    const customer = await userRepository.findById(customerId, {
      select: "-password",
      lean: true,
    });

    if (!customer || !hasRole(customer, ROLES.CUSTOMER)) {
      throw new AppError("Customer not found", 404);
    }

    const [jobSummaryResult, paymentSummaryResult, latestPaidPayment, recentJobs] =
      await Promise.all([
        jobRepository.model.aggregate([
          {
            $match: {
              customer: normalizedCustomerId,
            },
          },
          {
            $group: {
              _id: null,
              totalBookings: { $sum: 1 },
              completedBookings: {
                $sum: {
                  $cond: [{ $in: ["$status", ["completed", "paid"]] }, 1, 0],
                },
              },
              activeBookings: {
                $sum: {
                  $cond: [{ $in: ["$status", ["new", "assigned", "in_progress", "pending_verification"]] }, 1, 0],
                },
              },
              cancelledBookings: {
                $sum: {
                  $cond: [{ $eq: ["$status", "cancelled"] }, 1, 0],
                },
              },
              lastBookingAt: { $max: "$createdAt" },
            },
          },
        ]),
        paymentRepository.model.aggregate([
          {
            $match: {
              customer: normalizedCustomerId,
            },
          },
          {
            $group: {
              _id: null,
              totalSpent: {
                $sum: {
                  $cond: [{ $eq: ["$status", "paid"] }, "$amount", 0],
                },
              },
              paidOrders: {
                $sum: {
                  $cond: [{ $eq: ["$status", "paid"] }, 1, 0],
                },
              },
              outstandingBalance: {
                $sum: {
                  $cond: [{ $in: ["$status", ["pending", "authorized"]] }, "$amount", 0],
                },
              },
              lastPaymentAt: {
                $max: {
                  $cond: [{ $eq: ["$status", "paid"] }, "$paidAt", null],
                },
              },
            },
          },
        ]),
        paymentRepository.findOne(
          {
            customer: normalizedCustomerId,
            status: "paid",
          },
          {
            sort: { paidAt: -1, createdAt: -1 },
            lean: true,
            select: "paymentMethod paidAt amount status currency",
          }
        ),
        jobRepository.model
          .find({ customer: normalizedCustomerId })
          .sort({ createdAt: -1 })
          .limit(25)
          .populate([
            {
              path: "customer",
              select: "name email phone",
            },
            {
              path: "assignedWorker",
              select: "name email phone workerStatus skills",
            },
          ])
          .lean(),
      ]);

    const jobSummary = jobSummaryResult[0] || {};
    const paymentSummary = paymentSummaryResult[0] || {};
    const averageOrder =
      paymentSummary.paidOrders > 0 ? paymentSummary.totalSpent / paymentSummary.paidOrders : 0;

    return {
      customer: {
        ...customer,
        totalBookings: jobSummary.totalBookings || 0,
        completedBookings: jobSummary.completedBookings || 0,
        activeBookings: jobSummary.activeBookings || 0,
        cancelledBookings: jobSummary.cancelledBookings || 0,
        totalSpent: paymentSummary.totalSpent || 0,
        outstandingBalance: paymentSummary.outstandingBalance || 0,
        averageOrder,
        lastBookingAt: jobSummary.lastBookingAt || null,
        lastPaymentAt: paymentSummary.lastPaymentAt || null,
        lastPaymentMethod: latestPaidPayment?.paymentMethod || "unknown",
      },
      summary: {
        totalBookings: jobSummary.totalBookings || 0,
        completedBookings: jobSummary.completedBookings || 0,
        activeBookings: jobSummary.activeBookings || 0,
        cancelledBookings: jobSummary.cancelledBookings || 0,
        totalSpent: paymentSummary.totalSpent || 0,
        outstandingBalance: paymentSummary.outstandingBalance || 0,
        averageOrder,
        lastPaymentAt: paymentSummary.lastPaymentAt || null,
        lastPaymentMethod: latestPaidPayment?.paymentMethod || "unknown",
      },
      recentBookings: await jobService.attachOperationalDetails(recentJobs),
    };
  }

  buildBookingListFilter(query = {}) {
    const filter = {};
    const normalizedSearch = String(query.search || "").trim();

    if (query.status) {
      filter.status = query.status;
    }

    if (query.urgency) {
      filter.urgency = jobService.normalizeUrgency(query.urgency);
    }

    if (normalizedSearch) {
      if (mongoose.Types.ObjectId.isValid(normalizedSearch)) {
        filter._id = new mongoose.Types.ObjectId(normalizedSearch);
        return filter;
      }

      const searchPattern = { $regex: escapeRegex(normalizedSearch), $options: "i" };
      filter.$or = [
        { title: searchPattern },
        { fullName: searchPattern },
        { email: searchPattern },
        { phoneNumber: searchPattern },
        { serviceType: searchPattern },
        { city: searchPattern },
        { zipCode: searchPattern },
      ];
    }

    return filter;
  }

  async listBookings(query = {}) {
    const pagination = buildPagination(query);
    const filter = this.buildBookingListFilter(query);
    return jobRepository.findManyForAdminList(filter, {
      ...pagination,
      sort: { createdAt: -1 },
      select:
        "title serviceType streetAddress city state zipCode urgency status fullName email preferredDate preferredTime customer assignedWorker createdAt",
    });
  }

  async getBookingById(adminUser, jobId) {
    if (!hasRole(adminUser, ROLES.ADMIN)) {
      throw new AppError("Only admins can view booking details", 403);
    }

    const job = await jobRepository.findById(jobId, {
      lean: true,
      select:
        "title serviceType serviceId serviceCategoryLabel streetAddress city state zipCode urgency status estimatedPrice preferredDate preferredTime paymentStatus fullName phoneNumber email jobDescription photos pricing assignedWorker customer createdAt",
      populate: [
        {
          path: "customer",
          select: "name email phone",
        },
        {
          path: "assignedWorker",
          select: "name email phone skills",
        },
      ],
    });

    if (!job) {
      throw new AppError("Job not found", 404);
    }

    const [booking, payment] = await Promise.all([
      bookingRepository.findByJob(jobId, {
        lean: true,
        select:
          "job customer worker status scheduledDate scheduledTime notes workerCompletionNotes verificationPhotoUrls verificationVideoUrl verificationSubmittedAt verificationReviewedAt verificationApprovedAt verificationApprovedBy verificationNotes cancelReason startedAt completedAt cancelledAt createdAt",
      }),
      paymentRepository.findByJob(jobId, {
        lean: true,
        select:
          "job booking amount jobSubtotal bookingFee currency status platformFee platformFeePercentage workerPayout paidAt authorizedAt authorizationExpiresAt paymentMethod workerTransferStatus refundReason stripeRefundStatus stripeDisputeStatus createdAt",
      }),
    ]);
    const persistedPhotos = await jobService.persistJobPhotos(job.photos, {
      strict: false,
    });

    if (JSON.stringify(persistedPhotos) !== JSON.stringify(job.photos || [])) {
      await jobRepository.updateById(job._id, {
        photos: persistedPhotos,
      });
    }

    return {
      ...job,
      photos: persistedPhotos,
      booking: booking || null,
      payment: payment || null,
    };
  }

  async updateBookingStatus(adminUser, bookingId, status) {
    return bookingService.updateBookingStatusByAdmin(adminUser, bookingId, status);
  }

  async approveBookingCompletion(adminUser, bookingId, reviewNotes = "") {
    return bookingService.approveCompletionByAdmin(adminUser, bookingId, {
      reviewNotes,
    });
  }

  async listPayments(adminUser, query = {}) {
    return paymentService.listPayments(adminUser, query);
  }

  async listSupportConversations(query = {}) {
    const pagination = buildPagination(query);
    const filter = {};

    if (query.status) {
      filter.status = query.status;
    }

    if (query.search) {
      filter.$or = [
        { subject: { $regex: query.search, $options: "i" } },
        { requesterName: { $regex: query.search, $options: "i" } },
        { requesterEmail: { $regex: query.search, $options: "i" } },
      ];
    }

    return supportRepository.paginateConversations(filter, {
      ...pagination,
      sort: { lastMessageAt: -1 },
    });
  }

  async getPricingRules() {
    return getPricingConfig();
  }

  async updatePricingRules(adminUser, payload = {}) {
    if (!hasRole(adminUser, ROLES.ADMIN)) {
      throw new AppError("Only admins can update pricing rules", 403);
    }

    return savePricingConfig(payload);
  }

  async getSettings(adminUserId) {
    const [platformSettings, paymentSettings, notificationSettings, legalDocs, adminProfile] =
      await Promise.all([
      contentRepository.findByKey("platform-settings"),
      contentRepository.findByKey("payment-settings"),
      contentRepository.findByKey("notification-settings"),
      contentRepository.findByKey("legal-docs"),
      this.getAdminProfile(adminUserId),
    ]);

    return {
      adminProfile,
      platformSettings: this.normalizePlatformSettings(platformSettings?.value),
      paymentSettings: this.normalizePaymentSettings(paymentSettings?.value),
      notificationSettings: this.normalizeNotificationSettings(notificationSettings?.value),
      legalDocs: this.normalizeLegalDocs(legalDocs?.value),
    };
  }

  async updateSettings(adminUser, payload = {}) {
    const updates = [];

    if (payload.platformSettings) {
      updates.push(
        contentRepository.updateOne(
          { key: "platform-settings" },
          {
            key: "platform-settings",
            title: "Platform Settings",
            value: this.normalizePlatformSettings(payload.platformSettings),
            isPublic: false,
          },
          { upsert: true }
        )
      );
    }

    if (payload.paymentSettings) {
      updates.push(
        contentRepository.updateOne(
          { key: "payment-settings" },
          {
            key: "payment-settings",
            title: "Payment Settings",
            value: this.normalizePaymentSettings(payload.paymentSettings),
            isPublic: false,
          },
          { upsert: true }
        )
      );
    }

    if (payload.notificationSettings) {
      updates.push(
        contentRepository.updateOne(
          { key: "notification-settings" },
          {
            key: "notification-settings",
            title: "Notification Settings",
            value: this.normalizeNotificationSettings(payload.notificationSettings),
            isPublic: false,
          },
          { upsert: true }
        )
      );
    }

    if (payload.legalDocs) {
      updates.push(
        contentRepository.updateOne(
          { key: "legal-docs" },
          {
            key: "legal-docs",
            title: "Legal Documents",
            value: this.normalizeLegalDocs(payload.legalDocs),
            isPublic: true,
          },
          { upsert: true }
        )
      );
    }

    await Promise.all(updates);

    return this.getSettings(adminUser._id);
  }
}

module.exports = new AdminService();
